### ISSUE TITLE
Upgrade everything and possibility automatify

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js-plugins#23]
@morganherlocker has noticed that things have falled out of date here.

We built this a while ago with @aaronlidman and don't have an automatic update situation place because

* The modules we include don't all use npm
* They also sometimes don't use git tags either
* Bah humbug

Ideas for automation without guarantees of standardization graciously accepted

**Comment by jfirebaugh** [comment]
What's the percentage that are on npm or use GitHub releases versus the humbugs? Partial automation could be acceptable.

**Comment by jfirebaugh** [comment]
I'd like to keep this one open. Automation is a good idea and having the issue around might prompt someone to JFDI.

**Comment by tmcw** [comment]
Okay - it's been nearly a year since opening. JFDI doesn't usually happen but I will try to have faith.

**Comment by tmcw** [comment]
Closing; please open a new ticket if anyone has strategy & time for this.
