### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by domoritz** [mapbox/mapbox.js-plugins#25]
The links to the locate control files at https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/ return a 404. Also, you should use the special [mapbox css](https://github.com/mapbox/mapbox.js-plugins/blob/master/plugins/leaflet-locatecontrol/v0.42.0/L.Control.Locate.mapbox.css) and clean up the example. 

Reference https://github.com/domoritz/leaflet-locatecontrol/issues/118

**Comment by aaronlidman** [comment]
:+1: Lyzi fixed this here: https://github.com/mapbox/mapbox.js/pull/999
